// Browser-side calls to the finance API. Errors carry the server's message
// and per-field messages so forms can show them next to the right input.
import type { AttachmentDto, ExpenseDetailDto, ExpenseDto, PartnerInfo } from './db/financeRepo';
import type { ExpenseCategory, FundingSource, PaymentMethod, ReimbursementMethod } from './finance/types';

export type { AttachmentDto, ExpenseDetailDto, ExpenseDto };

export class ApiError extends Error {
  constructor(
    message: string,
    public status: number,
    public fieldErrors: Record<string, string[]> = {},
    public current?: unknown,
  ) {
    super(message);
  }
}

async function request<T>(path: string, init?: RequestInit): Promise<T> {
  let res: Response;
  try {
    res = await fetch(path, init);
  } catch {
    throw new ApiError('No connection. Check your signal and try again.', 0);
  }
  const body = await res.json().catch(() => null);
  if (!res.ok) {
    throw new ApiError(body?.error || `Request failed (${res.status})`, res.status, body?.fieldErrors ?? {}, body?.current);
  }
  return body as T;
}

const json = (method: string, data?: unknown): RequestInit => ({
  method,
  headers: { 'content-type': 'application/json' },
  body: data === undefined ? undefined : JSON.stringify(data),
});

export interface PartnerOption extends PartnerInfo {
  outstandingCents: number;
}

export function getPartners(): Promise<{ me: string; partners: PartnerOption[] }> {
  return request('/api/finance/partners');
}

export interface ExpenseListFilter {
  from?: string;
  to?: string;
  event?: number | 'general';
  paidBy?: string;
  limit?: number;
}

export function listExpenses(filter: ExpenseListFilter = {}): Promise<ExpenseDto[]> {
  const qs = new URLSearchParams();
  for (const [k, v] of Object.entries(filter)) if (v !== undefined && v !== '') qs.set(k, String(v));
  return request(`/api/expenses${qs.size ? `?${qs}` : ''}`);
}

export function getExpense(id: string): Promise<ExpenseDetailDto> {
  return request(`/api/expenses/${id}`);
}

export interface ExpenseFormValues {
  bookingId: number | null;
  category: ExpenseCategory;
  amountCents: number;
  taxCents: number;
  expenseDate: string;
  paidByEmail: string;
  paymentMethod: PaymentMethod;
  fundingSource: FundingSource;
  reimbursable: boolean;
  notes: string | null;
  receiptAttachmentId: string | null;
}

export function createExpense(id: string, values: ExpenseFormValues): Promise<ExpenseDetailDto> {
  return request('/api/expenses', json('POST', { id, ...values }));
}

export function updateExpense(id: string, values: ExpenseFormValues, expectedUpdatedAt: string): Promise<ExpenseDetailDto> {
  return request(`/api/expenses/${id}`, json('PATCH', { ...values, expectedUpdatedAt }));
}

export function deleteExpense(id: string): Promise<ExpenseDetailDto> {
  return request(`/api/expenses/${id}`, { method: 'DELETE' });
}

export function restoreExpense(id: string): Promise<ExpenseDetailDto> {
  return request(`/api/expenses/${id}/restore`, { method: 'POST' });
}

export function uploadReceipt(file: Blob, filename: string): Promise<AttachmentDto> {
  const form = new FormData();
  form.append('file', file, filename);
  return request('/api/attachments', { method: 'POST', body: form });
}

export function receiptUrl(attachmentId: string): string {
  return `/api/attachments/${attachmentId}`;
}

export interface ReimbursementFormValues {
  amountCents: number;
  reimbursedOn: string;
  method: ReimbursementMethod;
  notes: string | null;
}

// `id` is generated by the caller once per payment, so a retried save can't
// record the same payment twice.
export function addReimbursement(expenseId: string, id: string, values: ReimbursementFormValues): Promise<ExpenseDetailDto> {
  return request(`/api/expenses/${expenseId}/reimbursements`, json('POST', { id, ...values }));
}

export function voidReimbursement(expenseId: string, reimbursementId: string, reason: string): Promise<ExpenseDetailDto> {
  return request(`/api/expenses/${expenseId}/reimbursements/${reimbursementId}/void`, json('POST', { reason }));
}
