// Private receipt storage. Files never get a public URL: they're read back
// only through /api/attachments/[id], which checks the partner's session.
//
// Two backends, chosen by RECEIPT_STORAGE (or automatically):
//   vercel_blob — Vercel Blob with access: 'private' (production). Needs
//                 BLOB_READ_WRITE_TOKEN from a Blob store linked to the project.
//   local       — files under .data/receipts, for local development and
//                 tests only. Refuses to run on Vercel.
// The backend that stored a file is recorded on its attachments row, so a
// file is always read back from where it was written.
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join, resolve, sep } from 'node:path';
import { get, put } from '@vercel/blob';

export type StorageProvider = 'vercel_blob' | 'local';

export interface StoredFile {
  body: ReadableStream<Uint8Array>;
  contentType: string | null;
}

interface ReceiptStorage {
  provider: StorageProvider;
  put(key: string, bytes: Uint8Array, contentType: string): Promise<void>;
  get(key: string): Promise<StoredFile | null>;
}

const blobStorage: ReceiptStorage = {
  provider: 'vercel_blob',
  async put(key, bytes, contentType) {
    await put(key, Buffer.from(bytes), {
      access: 'private',
      contentType,
      addRandomSuffix: false, // the key already contains a random UUID
      allowOverwrite: false, // a receipt, once stored, is never replaced
    });
  },
  async get(key) {
    const result = await get(key, { access: 'private' });
    if (!result || !result.stream) return null;
    return { body: result.stream, contentType: result.blob.contentType };
  },
};

// The turbopackIgnore markers stop the bundler from tracing the whole
// project into the production functions because of these dynamic paths;
// the local backend is development-only.
function localRoot(): string {
  return resolve(/*turbopackIgnore: true*/ process.env.RECEIPT_LOCAL_DIR || join(process.cwd(), '.data', 'receipts'));
}

// Keys are generated by the server, but resolve defensively anyway so a
// key can never point outside the storage folder.
function localPath(key: string): string {
  const root = localRoot();
  const full = resolve(/*turbopackIgnore: true*/ root, key);
  if (!full.startsWith(root + sep)) throw new Error('Invalid storage key');
  return full;
}

const localStorage: ReceiptStorage = {
  provider: 'local',
  async put(key, bytes) {
    const path = localPath(key);
    await mkdir(/*turbopackIgnore: true*/ dirname(path), { recursive: true });
    await writeFile(/*turbopackIgnore: true*/ path, bytes, { flag: 'wx' }); // fail rather than overwrite
  },
  async get(key) {
    try {
      const bytes = await readFile(/*turbopackIgnore: true*/ localPath(key));
      return {
        body: new ReadableStream({
          start(controller) {
            controller.enqueue(new Uint8Array(bytes));
            controller.close();
          },
        }),
        contentType: null,
      };
    } catch (err) {
      if ((err as NodeJS.ErrnoException).code === 'ENOENT') return null;
      throw err;
    }
  },
};

export function storageFor(provider: StorageProvider): ReceiptStorage {
  if (provider === 'local') {
    if (process.env.VERCEL) throw new Error('Local receipt storage is not available on Vercel.');
    return localStorage;
  }
  if (!process.env.BLOB_READ_WRITE_TOKEN) {
    throw new Error('BLOB_READ_WRITE_TOKEN is not set. Create a Blob store in Vercel and link it to this project.');
  }
  return blobStorage;
}

// Where new uploads go.
export function activeStorage(): ReceiptStorage {
  const configured = process.env.RECEIPT_STORAGE;
  if (configured === 'local' || configured === 'vercel_blob') return storageFor(configured);
  if (configured) throw new Error(`Unknown RECEIPT_STORAGE "${configured}" (use vercel_blob or local).`);
  return storageFor(process.env.BLOB_READ_WRITE_TOKEN || process.env.VERCEL ? 'vercel_blob' : 'local');
}
